# Generated by Django 4.0.2 on 2022-02-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='first_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='last_name',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
