# Generated by Django 4.0.2 on 2022-02-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees_first_name_employees_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
