# Generated by Django 4.0.2 on 2022-02-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_employees_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
