# Generated by Django 4.0.2 on 2022-02-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employees_egn'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id2', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
