# Generated by Django 4.0.2 on 2022-02-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.AddField(
            model_name='employees',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Software Developer'), (2, 'Software Engineer'), (3, 'DevOps Specialist')], default=1),
            preserve_default=False,
        ),
    ]
