# Generated by Django 4.0.2 on 2022-02-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_department_alter_employees_egn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='employees.department'),
            preserve_default=False,
        ),
    ]
