# Generated by Django 4.0.2 on 2022-02-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_first_name_employee_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
