# Generated by Django 4.0.2 on 2022-02-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id2', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
            ],
        ),
    ]
