# Generated by Django 4.0.2 on 2022-02-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Software engineer'), (2, 'QA engineer'), (3, 'DevOps specialist')]),
        ),
    ]
