# Generated by Django 4.0.2 on 2022-02-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employee_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(choices=[('Soft_Uni', 'Soft_Uni'), ('Google', 'Google')], default='', max_length=8),
            preserve_default=False,
        ),
    ]
