# Generated by Django 4.0.2 on 2022-02-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.CharField(choices=[('Soft_Uni', 'Soft_Uni'), ('Google', 'Google'), ('Facebook', 'Facebook')], max_length=8),
        ),
    ]
