# Generated by Django 4.0.2 on 2022-02-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_department_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
